org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Ellenőrizd / frissítsd: https://fabricmc.net/develop  (Minecraft 1.21.11)
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_version=0.141.6+1.21.11

mod_version=1.3.0
maven_group=hu.feherhollo69
archives_base_name=cooldowntracker
